language: node_js
sudo: false
node_js:
- lts/*
cache:
  directories:
  - node_modules
before_install: npm install -g gulp-cli
deploy:
  provider: npm
  email:
    secure: GCJjVLTXFwaIMzDwRiBHciNW97JoRlZ0P9qb7VjXkH2DOlBxD4fjZ0oCdIOPo8Vk9Io1+H4FL4BjbyRgAbrXTBt288HQBrsOqm8uwjRPTvkuBm7pxOgzcTzmJ4r6aA50/CibH6znyBrxmqKnjKPMiTRbHUznNUGU1oeEhcRhpIAsQHj20cWjbQXvZIdI46OWkI5MaTMZTPbzGtjqxhjUwacYFzjEsg2iEQsM0Oal1VzjsPlSzw7ZrSiL4iWyE808aJMRuX30+U+mwkoTPiUITBp5X9f3d5OiNNB8k1cHRtugTlbqfHXSwGFcOP20uU4sVeUHG5HQ7U12l+QfcFRh1TnAc0/1YK9rekBZ8DCxDsb2Lu/8l6XyEjv+5ch3x/M/xpESrWkc0kAkhaKHDu5t7OkDH9eCBhIiQLsyvG8tgT7Q+H5TH5dfRFouFowqZlNqc+aydtMovoCepwf50gAPq4RKE+ui+Ultrlns4Qgnzk7m57VkpmsTVJkT8ALNvIDI1r4imdq3t9nxFBj4Cz3czn0iP33599JkjoE5Xe/W0BUfnMHwbL54Tsl91DPhQnFLLJWdlztBMPStkQxaCydSVI4+ItbRzmeFMNhfT1cwDGeeqts6HKovYIdDkod4E5hE6VdY0rQEezER3ZhfGvESYtdI4ohkvrnNpbq35j+9Uew=
  api_key:
    secure: yX6M9ycWbVCWqxkzRmybs9XzbmizqDfx3Le7Z32bD5Epnlv4+BRAhqVpQD1miIYyOr2Wsxvv/VO6ft33UNaFAuNyqdfd/tk2DLfKnD8cEZJ2QB2IMDL1/OV9Yp2tvwNse4nJPemRlL4/umUQl3OqFsYmPy10MmjdA4TwlK/vF37BYMSImXC90Ey98WfiMZ6SKvJvHGqPE6D7JzVkXAaQjq73c4qAAgEoCb2876NbL0ltYU+c7G97LyQ6p5r0PZdyOUlI0aMmDONe3pCs2AoI3CyyFsDvRZiJoXAaj/wuDMy4x9VaVVCXw0cAk4bIeLdi5j4TZqeTAtIWYwtl0LoeUE7Mngi01IAwBXXb9jsXUImNslYXYIlSm4/wtkDzYJBSO5nONiIJJoABQ40sV6kP7Cq8iaY4v24qLsPy1vzJzTpZXeGqglywrz9N+Iy08bYSmaNc+Mgax8laEb7kVZgbHxluBSP11T4oXwYd2iAqgenhHXcNoleBQG8vDIYoVZ8VjqPrmJ6fs8zcC+PQbEFeOE6Nv3zg+6cmIq13AW3QG/69Ux+qvZstwnVBbaW+bi/e5LAfFj/iqrM630mOYNiely69+KGBqgX0SVrdEwbze3kDVGdPeaJ4AjWiBklqPmN9yQifDRTeqfKV5vVXjSqBkMdgk6NFYckmS2gW5LtPtrQ=
  on:
    tags: true
