language: node_js
node_js:
- stable
before_install: npm install -g gulp-cli
deploy:
  provider: npm
  api_key:
    secure: fyX+2b37L5e2708zOL1zZJUd9tp7UbikdiKcKXy7JKN37KDlA1Ds9bFxA4mJkmllt1Hd2p22KwOiqAf3r1MTHVDjJ1iODjhdx89vyT6wbutolwonEE2m6Vo/qSKUhydZxFbEKgFE6jjlFmkJ7XNHn0QR6kXHjAsU0ZJSEYsauuGCePesSsuVrPNuhnrPJDs+7vEs2eSKioLcakF/F12YGULQ8r5hIMf/xQPF3qWvnv5cdTOzZ6tbIXpAdXl7ouFf852Dyq5CqqKjtkMRE2C+hT0xCJz0LylQ+NwCjUwBTk45lq0gc2apqaEZpAxIx0SN989DZ9mtAiByEsJnj/H5+J/7HAmE09v4q7VLiQhPPID0MOVB7vnq6UE6q+xKxipi0h3Qga+eUK4XIra2pim++UudgwggLimZIBNSTQebXjEfvgdCityC4V0mVuW2d+44UqnBUCvPSBh5bwLqiQ0bjD426Q/Z/JOLQnYzw0oAXqnRuUJdZu0hZ+OWa1tYLU6Tpg9kdjAJRM8kmqZ4D1G/s1xQcbDSB8B/yl/Wn1YnVkSumQ48CjxX169tq6sj/ruycYwqiGHXz9YSrcJ20zmHk2KZWcZQay8J/7rqzMsEgSlWbVjHhGHSijvvVtpr2WESlPuQ1wOruAoqpQ+rNnvJ01WArJaLJszDtqn3RrWHxtU=
  on:
    tags: true
  email:
    secure: HkKeWuU0fdX4TN8cqlniHt9hNWZ1MjS7CzJsg1hlsvKyI1VWXzSuZiyDD5/E7mj4cm5zdJCGUvydVkS6qeSzI30jBb1J6YqsqCTk8oVnUGoK/Pr1vv5THTEPU1axu4rGqXo0Zfzd2oEDsj+keG0F8/jwSzB2ldFg2BfI31ec7L4/CAn3mmQq/DR9kdVS7k9K0bvAxVlOq3oRH/y79K46fQYBlyDuivEiM8L1SjHl417y6qrZ2mQQCXyAufg5+TPFVJpPV70AzeAxn0hblOygZw1IJPkm3iMDFv9+iYD3CVgbECWh2UbpaAwfvxe52Dcbmw88mjghVcCDSL7cxYgc5PtiBg1HcvK+7Hs6+Op8xi+uNwh2J1ndJB7L4HUmtaYD5gkdPs3wHcGsw9/sD2BDv3hvjcKOp3+ytn4bC/HIUMD6xQnxd8z+I4jd3+HMk63/BdRDSlVPDUOr6JYacaMYTT/NVJRF9D+AchT1vjxLeMFZYSnkggrJHJ3oRn48/RS50lqGOjOcqnVTxzhYDkZpn4KMUJyeEBe3QKFfDkzvUE2IfEFsYUxMBPo7JjCPeotRrJ5GMgkEwqsIcYTPN1oyBsBy7GinH074yLOS2vss1cjORiwj1Op/CNl6AFBXkkmvh19xM/DOsDe6D196ervDkSS/U/RbJ/3/jSN99rO3VFA=
