language: node_js
sudo: false
node_js:
- lts/*
cache:
  directories:
    - "node_modules"
before_install: npm install -g gulp-cli
deploy:
  provider: npm
  email:
    secure: fd0qbj4J+g9WDwMl4SJ9rFdCIIK+TclCRcLVwlpSzSUiP5+oBnJDSeVqJyRqQPuhTG96K5n1BoIZS32YuF6Pjn6YDvRqgz1bJIfqCDt/JPiko+jW/Xtj2GSODat1PWg2NdOebQ5cqGiBGTKlp9X6Ri4SB9v0Q/7fvz9+VG3iMDtv3qYaub1C8HFQxRPw6k/DpOXJLShFAyKxwlbIwyUEtDeDIpPRqihycgkXGOkIR2ycQ19ecGOaHwo0yDn3Iy4eM9XVfzEffLnCkMx4p/2gkgEeDL02syY64cV/Fgtc2GFXK/SWXhoxvxVJB75fvwklXCYn2Rt7tNMhHvs3mkRSNEEF9ADpbi9fb9YvaFjvYKEakbl6jBdMP5vzER0HystArKM3B1tDlwjnYZL62fYYZN2vpt1ERPZzmTjjxe1i8+9QcCEyyLt/Hh5S9lM3btH2yhH8DEaXh9nr7ijca764vxSBPiDrswsnovccikVjuv/QYdQ+RWytPfjWudGnrSKsdPTba2frO0qlNlPGDW10Dl/fUIhGOgT3S73W5t77HCFxanP6yAvKG1zVXjOWfiG7Co6JT+0cwb/xWNTn2OmUMPDf/IDKD4Kk5oUckZk4RxhC4XweV7TLwqq1oUGRijSDP9gDUt4dPoMPgfBKEtApAlOb48zQ5nqUYl6+ANTDUfY=
  api_key:
    secure: XlSwLbT1bOIy5mKi/vYZuBfFVzaiTs/OVhoiT4Hf9K6enkOioooaa23Ne/7zkcC+wU9lorvQnOzbKlsRVrf+SJdt/KLdC/DmybaeU3oEJHeFE+YoXVsZA/cf+IjM2VkeU0SEm8rBDNCRjCqI9yST6cw+G4pCIVxvaz33mZAi4qpGMdxzUfHYYgjETP+oYCeFu/1KGcumQYF+l3Ygwd1D6ybRb3+a+41BpNspciNozLbcVafYi7D5TxAaJWrQLeDoznt3/JgOhEIxRm6zPBUWalxNy61179Pyz4pLEnHlIs0rH83sv1pTyMlP9l0zmzR30aH/tC8K8KtLlzlSgXBmmrcQype5UA2V83D3Bv6l1L5/wlIvAD3Zd3eg2Ic6DEFpnA8DSpc5N0SCArBuQl0hddVCNRX6XnAziJUmy2l2UPTHEYjo0sSrq2iO3N/09siu4zGjRqbnyN4qdby+rv3pzb0TytwW8WjvEu0As5FkFcB9iJF0e1HCMnB6axbTeYS8wNv5drzOIcZ6ctLFfGGuM27FNsvYgHuKE/VafZhsvZkFsnSqe2HYvKuDSE5xpDWEEnWY3LunQuJm4BKUjrlQilviGIbLGvJO3Da+V/ZhDwEmfoaotZSqSKZ8X1KLPmI4wbCNcjiKcFUoFoPsuA5QCzNEe/oxi+OAoNZV77NpOgI=
  on:
    tags: true
