language: node_js
sudo: false
node_js:
- lts/*
cache:
  directories:
  - node_modules
before_install: npm install -g gulp-cli
deploy:
  provider: npm
  email:
    secure: GCJjVLTXFwaIMzDwRiBHciNW97JoRlZ0P9qb7VjXkH2DOlBxD4fjZ0oCdIOPo8Vk9Io1+H4FL4BjbyRgAbrXTBt288HQBrsOqm8uwjRPTvkuBm7pxOgzcTzmJ4r6aA50/CibH6znyBrxmqKnjKPMiTRbHUznNUGU1oeEhcRhpIAsQHj20cWjbQXvZIdI46OWkI5MaTMZTPbzGtjqxhjUwacYFzjEsg2iEQsM0Oal1VzjsPlSzw7ZrSiL4iWyE808aJMRuX30+U+mwkoTPiUITBp5X9f3d5OiNNB8k1cHRtugTlbqfHXSwGFcOP20uU4sVeUHG5HQ7U12l+QfcFRh1TnAc0/1YK9rekBZ8DCxDsb2Lu/8l6XyEjv+5ch3x/M/xpESrWkc0kAkhaKHDu5t7OkDH9eCBhIiQLsyvG8tgT7Q+H5TH5dfRFouFowqZlNqc+aydtMovoCepwf50gAPq4RKE+ui+Ultrlns4Qgnzk7m57VkpmsTVJkT8ALNvIDI1r4imdq3t9nxFBj4Cz3czn0iP33599JkjoE5Xe/W0BUfnMHwbL54Tsl91DPhQnFLLJWdlztBMPStkQxaCydSVI4+ItbRzmeFMNhfT1cwDGeeqts6HKovYIdDkod4E5hE6VdY0rQEezER3ZhfGvESYtdI4ohkvrnNpbq35j+9Uew=
  api_key:
    secure: Zw3W0aIAF4EG8hMWiVvnRLEtn/5S0Gh8GRdesl7u1HJmAhmAC008yyoPJG08zUmfLPRYhmGoXTLa9GwCq0TPe0XZ9svyxOGexOBgD1MGUn2rPO9eemFlgPRWimf8VI5P/tB2MkGC8zxcMEZQr8oSZ8osuF8QWA0Sq+Grv+r7nersQ4PyYwuCjau/h43T88fxIIoquoHnsJS1O3VR1pXeYtM6gplUxuqD5KyxhNOSimQw7Jn14HXbSgfjssYL9xv/uTlM5TFWikWpLGj1tRhaVxauNfKLQFXaA0Fc1/jf+RGtK2V6pDvuGQD4Q84YqGvtn/IfOQAQqUx71zaYiQ3Z2MSQupPgGBAYdG7fqOhfvkp1hsZjPm8e0ubIViIIyaiMShGVh/og+OiCZ/yXdq+QJppv2ciZD1COq2t66j1bR3UNvrNZtgID3bI2S1RirIzR9RQIVgBIB1yfVnSXhk2ygZkAkQWs1Lskn/cdH/bdoV9Pue7QcWfQZmdMkEsEwbXdsN2jCfi+02BjWvDI0Mfgq/3zAeqYYcszzyR/UYhuNRQNmsoAg+IVSeSxq0nbRAZ7VYH2TKrd1OhxFfyQyUm+oqAoy4GC+lXXwmXPgW6u4dvHp08Os18810cFOLY1eFh/H8RZP/fyYuJbvW6qOY5D5PDl54qF4mS5xev+T8Di4fM=
  on:
    tags: true
